name: Update Gallery

on:
  push:
    paths:
      - "src/**"
  workflow_dispatch:

jobs:
  generate-gallery:
    runs-on: ubuntu-latest
    # Prevent running on commits that are just gallery updates
    if: "!contains(github.event.head_commit.message, '[gallery-update]')"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          # Use a token with write access to push the changes
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          fetch-depth: 0

      - name: Generate Thumbnails
        run: |
          sudo apt-get update && sudo apt-get install -y imagemagick
          mkdir -p src/thumbnails
          find src -maxdepth 1 -type f \( -name "*.png" -o -name "*.jpg" -o -name "*.jpeg" -o -name "*.gif" -o -name "*.webp" \) | while read img; do
            # Use a more efficient resize operation
            convert "$img" -resize 400x "src/thumbnails/$(basename "$img")"
          done

      - name: Run Script to Update Gallery
        run: |
          chmod +x generate_readme.sh
          ./generate_readme.sh

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # Add all changes, including new files in docs
          git add docs/js/main.js src/thumbnails
          # Check for changes before committing
          if ! git diff --staged --quiet; then
            git commit -m "Update gallery and thumbnails [gallery-update]"
            git push
          else
            echo "No changes to commit."
          fi
