name: Update README

on:
  push:
    branches:
      - main
  workflow_dispatch:
  # schedule:
  #   - cron: "0 0 * * *" # Runs daily at midnight UTC

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Generate thumbnails
        run: |
          sudo apt-get update && sudo apt-get install -y imagemagick
          mkdir -p src/thumbnails
          find src -maxdepth 1 -type f \( -name "*.png" -o -name "*.jpg" -o -name "*.jpeg" -o -name "*.gif" -o -name "*.webp" \) | while read img; do
            convert "$img" -resize 300x "src/thumbnails/$(basename "$img")"
          done

      - name: Run script to update README
        run: |
          chmod +x generate_readme.sh
          ./generate_readme.sh

      - name: Commit and push if changed
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-update README with wallpaper list" || exit 0
          git push
