name: Update Gallery and Sync to GitLab

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-gallery:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[gallery-update]')"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          fetch-depth: 0

      - name: Generate thumbnails
        run: |
          sudo apt-get update && sudo apt-get install -y imagemagick
          mkdir -p src/thumbnails
          find src -maxdepth 1 -type f \( -name "*.png" -o -name "*.jpg" -o -name "*.jpeg" -o -name "*.gif" -o -name "*.webp" \) | while read img; do
            convert "$img" -resize 400x "src/thumbnails/$(basename "$img")"
          done

      - name: Run script to update gallery
        run: |
          chmod +x generate_readme.sh
          ./generate_readme.sh

      - name: Commit and push if changed
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-update gallery with new wallpapers [gallery-update]" || exit 0
          git push
