name: Update Gallery

on:
  push:
    paths:
      - "src/**"
  workflow_dispatch:

jobs:
  generate-gallery:
    runs-on: ubuntu-latest
    # Prevent running on commits that are just gallery updates
    if: "!contains(github.event.head_commit.message, '[gallery-update]')"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          # Use a token with write access to push the changes
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          fetch-depth: 0

      - name: Install ImageMagick
        run: |
          sudo apt-get update && sudo apt-get install -y imagemagick

      - name: Run Script to Update Gallery and Thumbnails
        run: |
          chmod +x generate_readme.sh
          ./generate_readme.sh

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # Add the updated data file and the entire thumbnails directory
          git add docs/js/gallery-data.js src/.thumbnails
          # Check for changes before committing
          if ! git diff --staged --quiet; then
            git commit -m "Update gallery and thumbnails [gallery-update]"
            git push
          else
            echo "No changes to commit."
          fi